stages:
  - "test"
  - "build"
  - "deploy"

# Define defaults for all stages:
image: "node:14-alpine"
before_script:
  - "npm install"

build_npm:
  stage: "build"
  needs: []
  script:
    - "npm run build"
  rules:
    - if: "$CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH"

build_docker:
  stage: build
  needs: []
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:latest --cache=true --cache-copy-layers=true --cache-ttl=24h
  rules:
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"

pages:
  stage: "deploy"
  needs: []
  script:
    - "npm run build"
    - "apk add brotli && find ./public -type f -exec brotli -w 0 {} \\;"
  artifacts:
    paths:
      - "public"
  rules:
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
